### ISSUE TITLE
shience.tests does not use shience directly

### ISSUE THREAD

**Issue by MovGP0** [davezych/shience#14]
`Shience.Tests` downloads `Shience` from NuGet instead of targeting it directly. this way, changes cannot be tested immediately and the `[assembly:InternalsVisibleTo("...")]` attribute gets ignored.

**Comment by davezych** [comment]
Ha. How great. It's because the version on nuget is listed as `1.0.0-beta2`, and tests are targeting `1.0.0-*`. 

I need to think about what to do about the version on Nuget right now. It's listed as `beta2` just because I was just messing with project.json versioning. We really should roll back the version # to an alpha. `0.0.1-alpha` or something.

**Comment by MovGP0** [comment]
this is my first DNX project. I missed that one. will take a look on it next time.

**Comment by davezych** [comment]
I rolled back the version to `0.0.1`, and set tests to target specifically that version so it should pull it down locally.

**Comment by MovGP0** [comment]
I still experience the same issue. the project `Shience.Test` is not building, because it downloads the library from NuGet instead of using the local copy.

**Comment by MovGP0** [comment]
Solution: the dependency in the test project must be given without version number to use the local version: 

```json 
"dependencies": {
    "Shience": ""
  }
```
